version: "3"

services:
  mongo:
    image: mongo:4.4.0
    container_name: rest-api
    logging:
      driver: none
  server:
    build:
      context: .
      dockerfile: docker/dockerfile.dev
    container_name: app
    restart: always
    environment:
      MONGO_URL: "mongodb://mongo/api"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/rest-api
      - /usr/src/rest-api/node_modules
